#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Semiotic AI, Inc.
#
# SPDX-License-Identifier: Apache-2.0

# Writes deploy/values/generated/images.yaml for Argo Helm valueFiles.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

OUT="${ROOT}/deploy/values/generated/images.yaml"
SCENARIO_OUT="${ROOT}/deploy/values/generated/scenario.yaml"
mkdir -p "$(dirname "${OUT}")"

LAST_TAG_FILE="${ROOT}/deploy/values/generated/.last-image-tag"
TAG="${AGENTIUM_IMAGE_TAG:-}"
if [[ -f "${LAST_TAG_FILE}" ]]; then
  TAG="$(tr -d '[:space:]' <"${LAST_TAG_FILE}")"
fi
if [[ -z "${TAG}" ]]; then
  echo "render-values: no image tag — run just image-tag-nonce or set AGENTIUM_IMAGE_TAG" >&2
  exit 1
fi

REGISTRY_CONTAINER_HOST="${REGISTRY_CONTAINER_HOST:-k3d-agentium-registry}"
REGISTRY_CONTAINER_PORT="${REGISTRY_CONTAINER_PORT:-5000}"
IMAGE_NAME="${IMAGE_NAME:-agentium-runner}"
IN_CLUSTER_REGISTRY="${IN_CLUSTER_REGISTRY:-${REGISTRY_CONTAINER_HOST}:${REGISTRY_CONTAINER_PORT}}"

cat >"${OUT}" <<EOF
# Generated by scripts/e2e-k8s/render-values.sh — do not edit by hand
runner:
  image:
    repository: ${IN_CLUSTER_REGISTRY}/${IMAGE_NAME}
    tag: ${TAG}
    pullPolicy: Always
EOF

if [[ ! -f "${SCENARIO_OUT}" ]]; then
  printf '%s\n' '# no scenario overrides' >"${SCENARIO_OUT}"
fi

echo "render-values: wrote ${OUT} (tag=${TAG})"
