//! Common test utilities and shared modules.

pub use crate::support::tools::*;
mod a2a_test_helpers;
pub use a2a_test_helpers::{
    chunk_content, chunks_from_responses, first_message_text_from_stream,
    first_task_id_from_stream, is_error_response, message_texts_from_chunks, send_stream_request,
    user_message,
};
mod test_tools;
// Fixture helpers
use std::{path::PathBuf, sync::Arc};

use baml_rt::{A2aAgent, QuickJSConfig, baml::BamlRuntimeManager, quickjs_bridge::QuickJSBridge};
use baml_rt_provenance::GraphqliteStoreBuilder;
pub use test_tools::{
    AddNumbersInput, AddNumbersOutput, AddNumbersTool, DelayedResponseTool, UppercaseTool,
    WeatherTool,
};
use tokio::sync::Mutex;

pub fn fixture_path(relative_path: &str) -> PathBuf {
    workspace_root()
        .join("tests")
        .join("fixtures")
        .join(relative_path)
}

pub fn agent_fixture(name: &str) -> PathBuf {
    fixture_path(&format!("agents/{}", name))
}

/// Assert that fixture TypeScript runtime declarations exist.
///
/// Scans `tests/fixtures/agents/` for directories containing `baml_src/`
/// and asserts each also has `src/baml-runtime.d.ts`. With nextest, these
/// are generated by the `regen-fixtures` setup script (see
/// `.config/nextest.toml`). For plain `cargo test`, run the binary
/// manually first: `cargo run -p baml-rt-builder --bin regen_fixtures`.
pub fn ensure_fixture_runtime_types() {
    let agents_dir = workspace_root()
        .join("tests")
        .join("fixtures")
        .join("agents");
    let mut missing = Vec::new();
    let entries = std::fs::read_dir(&agents_dir).unwrap_or_else(|e| {
        panic!(
            "Cannot read fixture agents directory {}: {e}",
            agents_dir.display()
        );
    });
    for entry in entries {
        let entry = entry.expect("read fixture entry");
        let path = entry.path();
        if path.join("baml_src").is_dir() && !path.join("src").join("baml-runtime.d.ts").exists() {
            missing.push(entry.file_name().to_string_lossy().into_owned());
        }
    }
    if !missing.is_empty() {
        missing.sort();
        panic!(
            "Missing baml-runtime.d.ts for fixtures: {missing:?}\n\
             Run: cargo run -p baml-rt-builder --bin regen_fixtures"
        );
    }
}

pub fn setup_baml_runtime(schema_path: &str) -> Arc<Mutex<BamlRuntimeManager>> {
    let mut manager = BamlRuntimeManager::new().expect("Should create manager");
    manager
        .load_schema(schema_path)
        .expect("Should load schema");
    Arc::new(Mutex::new(manager))
}

pub fn setup_baml_runtime_manager(schema_path: &str) -> BamlRuntimeManager {
    let mut manager = BamlRuntimeManager::new().expect("Should create manager");
    manager
        .load_schema(schema_path)
        .expect("Should load schema");
    manager
}

pub fn setup_baml_runtime_manager_default() -> BamlRuntimeManager {
    setup_baml_runtime_manager(
        workspace_root()
            .join("baml_src")
            .to_str()
            .expect("Workspace baml_src path should be valid"),
    )
}

pub fn setup_baml_runtime_default() -> Arc<Mutex<BamlRuntimeManager>> {
    setup_baml_runtime(
        workspace_root()
            .join("baml_src")
            .to_str()
            .expect("Workspace baml_src path should be valid"),
    )
}

pub fn setup_baml_runtime_from_fixture(fixture_name: &str) -> Arc<Mutex<BamlRuntimeManager>> {
    let agent_dir = agent_fixture(fixture_name);
    assert!(
        agent_dir.join("baml_src").exists(),
        "{} fixture must have baml_src directory",
        fixture_name
    );
    setup_baml_runtime(agent_dir.to_str().expect("Fixture path should be valid"))
}

/// QuickJS config for tests. Must accommodate combined retries (parse + BAML client) which can exceed 15s.
fn quickjs_config_for_tests() -> QuickJSConfig {
    QuickJSConfig::new().with_max_attempts_ms(Some(45_000))
}

pub async fn setup_bridge(baml_manager: Arc<Mutex<BamlRuntimeManager>>) -> QuickJSBridge {
    use baml_rt_core::{
        bus::{BusWithEffects, EffectEmitter, EffectLiveness},
        ids::AgentId,
    };
    use uuid::Uuid;
    // Generate a temporary agent_id for test context
    let temp_agent_id = AgentId::from_uuid(baml_rt_core::ids::UuidId::new(Uuid::new_v4()));
    let config = quickjs_config_for_tests();
    // Keep effect emission/liveness wiring aligned with runtime builder semantics.
    let effect_bus = Arc::new(BusWithEffects::new());
    {
        let mut manager = baml_manager.lock().await;
        manager.set_effect_emitter(effect_bus.clone() as Arc<dyn EffectEmitter>);
    }
    let mut bridge = QuickJSBridge::new_with_config(baml_manager, temp_agent_id, config)
        .await
        .expect("Create QuickJS bridge");
    bridge.set_effect_liveness(effect_bus as Arc<dyn EffectLiveness>);
    bridge
        .register_baml_functions()
        .await
        .expect("Register BAML functions");
    bridge
}

pub fn require_api_key() -> String {
    let _ = dotenvy::dotenv();
    let api_key = std::env::var("OPENROUTER_API_KEY")
        .expect("OPENROUTER_API_KEY environment variable must be set");
    assert!(!api_key.is_empty(), "OPENROUTER_API_KEY must not be empty");
    api_key
}

pub fn ensure_baml_src_exists() -> bool {
    let baml_src = workspace_root().join("baml_src");
    if !baml_src.exists() {
        println!("Skipping test: baml_src directory not found");
        return false;
    }
    true
}

pub fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("test-support crate should be under crates/")
        .to_path_buf()
}

/// Temporarily sets an environment variable for the lifetime of this guard.
///
/// Restores the previous value on drop.
#[derive(Debug)]
pub struct TempEnvVar {
    key: String,
    previous: Option<String>,
}

impl TempEnvVar {
    pub fn set(key: &str, value: &str) -> Self {
        let previous = std::env::var(key).ok();
        // SAFETY: test helper used in controlled test code; callers must avoid
        // concurrent mutation of the same env key from multiple threads.
        unsafe {
            std::env::set_var(key, value);
        }
        Self {
            key: key.to_string(),
            previous,
        }
    }

    pub fn remove(key: &str) -> Self {
        let previous = std::env::var(key).ok();
        // SAFETY: test helper used in controlled test code; callers must avoid
        // concurrent mutation of the same env key from multiple threads.
        unsafe {
            std::env::remove_var(key);
        }
        Self {
            key: key.to_string(),
            previous,
        }
    }
}

impl Drop for TempEnvVar {
    fn drop(&mut self) {
        match &self.previous {
            Some(value) => {
                // SAFETY: mirrors set/remove safety note above.
                unsafe {
                    std::env::set_var(&self.key, value);
                }
            }
            None => {
                // SAFETY: mirrors set/remove safety note above.
                unsafe {
                    std::env::remove_var(&self.key);
                }
            }
        }
    }
}

/// Asserts that a tool is visible in QuickJS (either as a JS tool in `__js_tools` or as a Rust tool via `openToolSession`).
/// Requires `scope` because the check runs an async IIFE that returns a promise; evaluate() must receive a scope to poll it.
pub async fn assert_tool_registered_in_js(
    bridge: &mut QuickJSBridge,
    tool_name: &str,
    scope: &baml_rt_core::context::InvocationScope,
) {
    let js_code = format!(
        r#"
        (async () => {{
            const jsTools = globalThis.__js_tools || {{}};
            if (typeof jsTools["{}"] === 'function') {{
                return JSON.stringify({{
                    toolExists: true,
                    source: "js"
                }});
            }}
            try {{
                const session = await openToolSession("{}");
                return JSON.stringify({{
                    toolExists: true,
                    source: "rust",
                    sessionId: session.sessionId
                }});
            }} catch (error) {{
                return JSON.stringify({{
                    toolExists: false,
                    error: error.toString()
                }});
            }}
        }})()
        "#,
        tool_name, tool_name
    );
    let result = bridge.evaluate(Some(scope), &js_code).await.unwrap_or_else(|e| {
        panic!(
            "Tool '{}' registration check failed: evaluate returned error (includes raw response if parse failed): {}",
            tool_name, e
        );
    });
    let obj = result.as_object().expect("Expected object");
    let tool_exists = obj
        .get("toolExists")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    let error_detail = obj
        .get("error")
        .and_then(|v| v.as_str())
        .unwrap_or("(no error detail)");
    assert!(
        tool_exists,
        "Tool '{}' should be registered in QuickJS. Error: {}. Full result: {:?}",
        tool_name, error_detail, obj
    );
}

/// In-memory GraphQLite store for tests that build A2aAgent (persistent mode required).
pub fn test_graphqlite_store() -> std::sync::Arc<baml_rt_provenance::GraphqliteProvenanceStore> {
    GraphqliteStoreBuilder::in_memory()
        .build()
        .expect("in-memory provenance store for test")
}

/// Builds a minimal A2aAgent for malformed/error-path A2A tests: no BAML schema or tools.
/// Uses BusWithEffects and QuickJSConfig with max_attempts_ms(15_000).
pub async fn build_minimal_a2a_agent(init_js: &str) -> A2aAgent {
    A2aAgent::builder()
        .with_init_js(init_js)
        .with_effect_emitter(Arc::new(baml_rt_core::bus::BusWithEffects::new()))
        .with_quickjs_config(QuickJSConfig::new().with_max_attempts_ms(Some(15_000)))
        .with_graphqlite_store(test_graphqlite_store())
        .build()
        .await
        .expect("build minimal a2a agent")
}

/// Builds an A2aAgent for contract tests: stream-baml-tool fixture, CalculatorTool,
/// test QuickJS config. Call `ensure_fixture_runtime_types()` before this if not already done.
/// Returns the agent; tests create scope via `InvocationScope::synthetic_message(agent.agent_id().clone())`.
pub async fn setup_stream_baml_tool_agent_for_contract(init_js: Option<&str>) -> A2aAgent {
    let mut baml_manager = BamlRuntimeManager::new().expect("create manager");
    let agent_dir = agent_fixture("stream-baml-tool");
    baml_manager
        .load_schema(agent_dir.to_str().expect("fixture path valid"))
        .expect("load schema");
    baml_manager
        .register_tool(CalculatorTool)
        .await
        .expect("register CalculatorTool");
    let config = QuickJSConfig::new().with_max_attempts_ms(Some(45_000));
    let mut builder = A2aAgent::builder()
        .with_runtime_manager(baml_manager)
        .with_effect_emitter(Arc::new(baml_rt_core::bus::BusWithEffects::new()))
        .with_quickjs_config(config)
        .with_graphqlite_store(test_graphqlite_store());
    if let Some(js) = init_js {
        builder = builder.with_init_js(js);
    }
    builder.build().await.expect("build A2aAgent")
}

/// Asserts the invocation result contract: value is an object, has no "success" wrapper,
/// and has "steps" (plan) or "result"/"formatted" (tool output). Panics with CONTRACT VIOLATION message on failure.
pub fn assert_result_contract_actual_result(val: &serde_json::Value) {
    assert!(
        val.is_object(),
        "CONTRACT VIOLATION: Expected actual result (object), got: {:?}",
        val
    );
    let obj = val.as_object().unwrap();
    assert!(
        !obj.contains_key("success"),
        "CONTRACT VIOLATION: Result must not be wrapped in success object, got: {:?}",
        val
    );
    let has_steps = val.get("steps").and_then(|v| v.as_array()).is_some();
    let has_tool_output = obj.contains_key("result") || obj.contains_key("formatted");
    assert!(
        has_steps || has_tool_output,
        "CONTRACT VIOLATION: Expected object with 'steps' or 'result'/'formatted', got: {:?}",
        val
    );
}
