#!/usr/bin/env bash
# Sync deploy/argocd/track.json + deploy/values/dev/images.yaml.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

die() {
  echo "set-deploy-ref: $*" >&2
  exit 1
}

require_cmd python3

GIT_REF="${1:-}"
IMG_TAG="${2:-${1:-}}"
[[ -n "${GIT_REF}" ]] || die "usage: set-deploy-ref.sh <git-ref> [image-tag]"

TRACK="${ROOT}/deploy/argocd/track.json"
IMAGES="${ROOT}/deploy/values/dev/images.yaml"
[[ -f "${TRACK}" ]] || die "missing ${TRACK}"

export AGENTIUM_SET_ROOT="${ROOT}"
export AGENTIUM_SET_GIT_REF="${GIT_REF}"
export AGENTIUM_SET_IMG_TAG="${IMG_TAG}"

python3 <<'PY'
import json
import os
from pathlib import Path

root = Path(os.environ["AGENTIUM_SET_ROOT"])
git_ref = os.environ["AGENTIUM_SET_GIT_REF"]
img_tag = os.environ["AGENTIUM_SET_IMG_TAG"]

track_path = root / "deploy/argocd/track.json"
images_path = root / "deploy/values/dev/images.yaml"

with open(track_path) as f:
    track = json.load(f)
track["targetRevision"] = git_ref
track["imageTag"] = img_tag
with open(track_path, "w") as f:
    json.dump(track, f, indent=2)
    f.write("\n")

images_path.write_text(
    f"""# Auto-generated by scripts/release/set-deploy-ref.sh — do not edit tags by hand.
runner:
  image:
    repository: ghcr.io/semiotic-agentium/agentium-runner
    tag: {img_tag}
    pullPolicy: Always
"""
)
print(f"set-deploy-ref: track.json → {git_ref}, dev/images.yaml → {img_tag}")
PY
