//! Rendering BAML definition structs into BAML text.

use std::fmt::Write;

use crate::types::{
    BamlClassDef, BamlDefinition, BamlEnumDef, BamlFieldDef, BamlUnionDef, BamlVariantDef,
};

/// Render a single `BamlDefinition` to BAML text.
#[must_use]
pub fn render_definition(def: &BamlDefinition) -> String {
    match def {
        BamlDefinition::Class(c) => render_class(c),
        BamlDefinition::Enum(e) => render_enum(e),
        BamlDefinition::Union(u) => render_union(u),
    }
}

/// Render multiple definitions into a complete `.baml` file body.
///
/// Definitions are separated by blank lines. A leading comment marks the
/// file as auto-generated.
#[must_use]
pub fn render_baml_types(defs: &[BamlDefinition]) -> String {
    let mut out = String::from("// Auto-generated by baml-derive — do not edit.\n\n");
    for (i, def) in defs.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&render_definition(def));
        out.push('\n');
    }
    out
}

fn render_class(class: &BamlClassDef) -> String {
    let mut out = String::new();

    if let Some(doc) = class.doc {
        render_doc_comment(&mut out, doc);
    }

    let _ = writeln!(out, "class {} {{", class.name);

    for field in &class.fields {
        render_field(&mut out, field);
    }

    if class.dynamic {
        out.push_str("  @@dynamic\n");
    }

    out.push('}');
    out
}

fn render_field(out: &mut String, field: &BamlFieldDef) {
    if field.skip {
        // Skipped fields are omitted entirely.
        return;
    }

    let _ = write!(out, "  {} {}", field.name, field.baml_type);

    if let Some(alias) = field.alias {
        let _ = write!(out, " @alias(\"{alias}\")");
    }
    if let Some(desc) = field.description {
        let _ = write!(out, " @description(\"{desc}\")");
    }

    out.push('\n');
}

fn render_enum(enum_def: &BamlEnumDef) -> String {
    let mut out = String::new();

    if let Some(doc) = enum_def.doc {
        render_doc_comment(&mut out, doc);
    }

    let _ = writeln!(out, "enum {} {{", enum_def.name);

    for variant in &enum_def.variants {
        render_variant(&mut out, variant);
    }

    out.push('}');
    out
}

fn render_variant(out: &mut String, variant: &BamlVariantDef) {
    if variant.skip {
        return;
    }

    let _ = write!(out, "  {}", variant.name);

    if let Some(alias) = variant.alias {
        let _ = write!(out, " @alias(\"{alias}\")");
    }
    if let Some(desc) = variant.description {
        let _ = write!(out, " @description(\"{desc}\")");
    }

    out.push('\n');
}

fn render_union(union_def: &BamlUnionDef) -> String {
    let mut out = String::new();

    if let Some(doc) = union_def.doc {
        render_doc_comment(&mut out, doc);
    }

    let variants = union_def.variants.join(" | ");
    let _ = write!(out, "type {} = {}", union_def.name, variants);
    out
}

/// Write `/// doc` lines as BAML `/// ` doc comments.
fn render_doc_comment(out: &mut String, doc: &str) {
    for line in doc.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            out.push_str("///\n");
        } else {
            let _ = writeln!(out, "/// {trimmed}");
        }
    }
}
