// SPDX-FileCopyrightText: 2026 Semiotic AI, Inc.
//
// SPDX-License-Identifier: Apache-2.0

//! Utilities for rendering multiple TypeScript declarations into a single file.

use crate::TsType;

/// Render TypeScript declarations for a slice of `ts_decl()` results into a
/// complete `.d.ts` file body.
///
/// Declarations are separated by blank lines. A leading comment marks the file
/// as auto-generated. `None` entries (unit types) are silently skipped.
#[must_use]
pub fn render_ts_declarations(decls: &[Option<String>]) -> String {
    let mut out = String::from("// Auto-generated by baml-derive — do not edit.\n\n");
    let mut first = true;
    for decl in decls.iter().flatten() {
        if !first {
            out.push('\n');
        }
        out.push_str(decl);
        out.push('\n');
        first = false;
    }
    out
}

/// Collect the TypeScript declaration for `T`, returning `None` for unit types.
///
/// Convenience wrapper around `<T as TsType>::ts_decl()` that can be called
/// without an explicit `TsType` bound on the call site.
pub fn ts_decl_for<T: TsType>() -> Option<String> {
    T::ts_decl()
}

/// Return the TypeScript type name for `T`.
pub fn ts_name_for<T: TsType>() -> &'static str {
    T::ts_type_name()
}
