// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScopeEchoOutput = { context_id: string | null, message_id: string | null, task_id: string | null, };
