//! BAML tool interface generation with FSM-aware prompting hints
//!
//! Generates BAML tool interface files with detailed descriptions and examples
//! following Anthropic's best practices for tool use prompting.

use std::collections::{HashMap, HashSet};

use baml_rt_tools::{tool_catalog::resolve_manifest_tools, tools::ToolFunctionMetadata};
use baml_tools_calculator as _;
use serde_json::Value;

use crate::builder::{
    error::{Result, write_line},
    schema_to_baml,
};

/// Generate BAML tool interface file with FSM-aware prompting hints
pub fn render_baml_tool_interfaces(tool_names: &[String]) -> Result<String> {
    // Force link so inventory sees these metadata registrations (regen_fixtures + builder).
    let _ = baml_tools_calculator::support_calculate_metadata;
    let _ = baml_rt_tools_claude::metadata::claude_dev_metadata;
    let _ = baml_tools_system::metadata::system_internal_a2a_metadata;
    #[cfg(feature = "clickup")]
    let _ = baml_tools_clickup::clickup_metadata;
    #[cfg(feature = "notion")]
    let _ = baml_tools_notion::notion_metadata;
    let tool_metadata = resolve_manifest_tools(tool_names)?;

    let mut output = String::new();

    // Header with FSM documentation
    write_line(&mut output, "// Auto-generated tool interfaces")?;
    write_line(
        &mut output,
        "// This file is auto-generated - do not edit manually",
    )?;
    write_line(&mut output, "")?;
    write_line(
        &mut output,
        "// FSM (Finite State Machine) Tool Session Protocol:",
    )?;
    write_line(
        &mut output,
        "// All host tools use a session-based FSM with strict state transitions:",
    )?;
    write_line(
        &mut output,
        "// 1. Open: Must be the FIRST step - opens a tool session",
    )?;
    write_line(
        &mut output,
        "// 2. Send: Can only occur AFTER Open - sends input to the session",
    )?;
    write_line(
        &mut output,
        "// 3. Next: Retrieves output from the session (after Send)",
    )?;
    write_line(&mut output, "// 4. Finish: Closes the session gracefully")?;
    write_line(&mut output, "// 5. Abort: Closes the session with an error")?;
    write_line(&mut output, "//")?;
    write_line(&mut output, "// CRITICAL FSM RULES:")?;
    write_line(&mut output, "// - Open MUST come before any Send step")?;
    write_line(
        &mut output,
        "// - Open may include 'initial_input' only when the step schema defines that field",
    )?;
    write_line(
        &mut output,
        "// - Send uses 'input' field (for subsequent inputs)",
    )?;
    write_line(
        &mut output,
        "// - After Send, call Next to retrieve results",
    )?;
    write_line(
        &mut output,
        "// - Always Finish or Abort to close the session",
    )?;
    write_line(&mut output, "")?;

    // Generate ToolSessionOp enum with descriptions
    write_line(&mut output, "enum ToolSessionOp {")?;
    write_line(
        &mut output,
        "  Open @description(\"Open a new tool session. MUST be the first step in any plan. Include 'initial_input' only when the step schema defines that field.\")",
    )?;
    write_line(
        &mut output,
        "  Send @description(\"Send input to an already-open session. Can ONLY be used after an Open step. Use 'input' field (NOT 'initial_input').\")",
    )?;
    write_line(
        &mut output,
        "  Next @description(\"Retrieve the next output from the session. Call this after Send to get results. For streaming tools, call Next multiple times until Done.\")",
    )?;
    write_line(
        &mut output,
        "  Finish @description(\"Close the session gracefully after completing all operations. Always call Finish when done with a tool session.\")",
    )?;
    write_line(
        &mut output,
        "  Abort @description(\"Close the session with an error. Use this if something went wrong and you need to terminate the session.\")",
    )?;
    write_line(&mut output, "}")?;
    write_line(&mut output, "")?;

    // --- Domain type generation ---
    //
    // Tools that carry a `baml_decl` (generated by `#[derive(BamlType)]`) emit
    // their type declarations directly. Tools without `baml_decl` fall back to
    // the `schema_to_baml` JSON Schema conversion pipeline.
    let mut emitted_decl_types: HashSet<String> = HashSet::new();
    let mut macro_decls = String::new();

    // Pass 1: collect pre-rendered BAML declarations from BamlType-enabled tools.
    for tool in &tool_metadata {
        if let Some(decl) = &tool.baml_decl {
            // Track the type names from this tool so schema_to_baml skips them.
            emitted_decl_types.insert(tool.input_type.name.clone());
            emitted_decl_types.insert(tool.output_type.name.clone());
            if tool.open_input_type.name != "()" {
                emitted_decl_types.insert(tool.open_input_type.name.clone());
            }

            if !macro_decls.is_empty() {
                macro_decls.push('\n');
            }
            macro_decls.push_str(decl);
            macro_decls.push('\n');
        }
    }

    if !macro_decls.is_empty() {
        write_line(
            &mut output,
            "// Domain types generated from #[derive(BamlType)]",
        )?;
        write_line(&mut output, &macro_decls)?;
    }

    // Pass 2: for tools WITHOUT baml_decl, fall back to schema_to_baml.
    let mut schemas = HashMap::new();
    let mut type_names = HashMap::new();

    for tool in &tool_metadata {
        // Skip tools that already provided their types via baml_decl.
        if tool.baml_decl.is_some() {
            continue;
        }

        extract_nested_schemas(&tool.input_schema, &mut schemas, &mut type_names);
        extract_nested_schemas(&tool.output_schema, &mut schemas, &mut type_names);
        if tool.open_input_type.name != "()" {
            extract_nested_schemas(&tool.open_input_schema, &mut schemas, &mut type_names);
        }

        // Only add schemas for types not already emitted by baml_decl.
        if !emitted_decl_types.contains(&tool.input_type.name) {
            schemas.insert(tool.input_type.name.clone(), tool.input_schema.clone());
            type_names.insert(tool.input_type.name.clone(), tool.input_type.name.clone());
        }

        if !emitted_decl_types.contains(&tool.output_type.name) {
            schemas.insert(tool.output_type.name.clone(), tool.output_schema.clone());
            type_names.insert(tool.output_type.name.clone(), tool.output_type.name.clone());
        }

        if tool.open_input_type.name != "()"
            && !emitted_decl_types.contains(&tool.open_input_type.name)
        {
            schemas.insert(
                tool.open_input_type.name.clone(),
                tool.open_input_schema.clone(),
            );
            type_names.insert(
                tool.open_input_type.name.clone(),
                tool.open_input_type.name.clone(),
            );
        }
    }

    if !schemas.is_empty() {
        let domain_types = schema_to_baml::generate_baml_types_from_schemas(&schemas, &type_names)?;
        if !domain_types.is_empty() {
            write_line(&mut output, "// Domain types generated from JSON schemas")?;
            write_line(&mut output, &domain_types)?;
        }
    }

    for tool in &tool_metadata {
        generate_tool_baml_interface(&mut output, tool)?;
        write_line(&mut output, "")?;
    }

    Ok(output)
}

fn generate_tool_baml_interface(output: &mut String, tool: &ToolFunctionMetadata) -> Result<()> {
    // Use the derived class name from metadata
    let class_name = &tool.class_name;

    // Use the actual type names from metadata
    let open_input_type_name = &tool.open_input_type.name;
    let input_type_name = &tool.input_type.name;

    let open_step_name = format!("{}OpenStep", class_name);
    let send_step_name = format!("{}SendStep", class_name);
    let next_step_name = format!("{}NextStep", class_name);
    let finish_step_name = format!("{}FinishStep", class_name);
    let abort_step_name = format!("{}AbortStep", class_name);
    let step_union_name = format!("{}SessionStep", class_name);
    let plan_type_name = format!("{}SessionPlan", class_name);
    let access_note = tool
        .access
        .map(|access| format!(" Access: {}.", access))
        .unwrap_or_default();

    // Generate distinct step types for each FSM operation
    write_line(output, &format!("class {} {{", open_step_name))?;
    write_line(output, "  op \"Open\"")?;
    // Only include initial_input if it's not unit type (void/() - skip field entirely)
    if open_input_type_name != "()"
        && open_input_type_name != "null"
        && open_input_type_name != "void"
    {
        write_line(
            output,
            &format!(
                "  initial_input {}? @description(\"Optional open-time configuration payload for the session. This is used only by Open and is not auto-sent as a Send input.\")",
                open_input_type_name
            ),
        )?;
    }
    write_line(
        output,
        "  reason string? @description(\"Optional explanation for this step.\")",
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", send_step_name))?;
    write_line(output, "  op \"Send\"")?;
    write_line(
        output,
        &format!(
            "  input {} @description(\"Input to send to the already-open session.\")",
            input_type_name
        ),
    )?;
    write_line(
        output,
        "  reason string? @description(\"Optional explanation for this step.\")",
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", next_step_name))?;
    write_line(output, "  op \"Next\"")?;
    write_line(
        output,
        "  reason string? @description(\"Optional explanation for this step.\")",
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", finish_step_name))?;
    write_line(output, "  op \"Finish\"")?;
    write_line(
        output,
        "  reason string? @description(\"Optional explanation for this step.\")",
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", abort_step_name))?;
    write_line(output, "  op \"Abort\"")?;
    write_line(
        output,
        "  reason string? @description(\"Optional explanation for aborting the session.\")",
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    // Generate union type for all step types
    write_line(
        output,
        &format!(
            "type {} = {} | {} | {} | {} | {}",
            step_union_name,
            open_step_name,
            send_step_name,
            next_step_name,
            finish_step_name,
            abort_step_name
        ),
    )?;
    write_line(output, "")?;

    // Generate session plan with FSM guidance and example. Runtime resolves the tool from the
    // builder-generated manifest mapping (function name -> plan type).
    write_line(output, &format!("class {} {{", plan_type_name))?;
    write_line(
        output,
        &format!(
            "  steps {}[] @description(\"Array of FSM steps. MUST follow this strict order: 1) Open (include initial_input only when the schema defines it), 2) Send (with input), 3) Next (to retrieve results), 4) Finish or Abort (to close). Runtime resolves this plan to a tool via builder-generated function->plan mapping (session_plan_functions.json). Example: [{{op: \\\"Open\\\"}}, {{op: \\\"Send\\\", input: {{...}}}}, {{op: \\\"Next\\\"}}, {{op: \\\"Finish\\\"}}].{}\")",
            step_union_name, access_note
        ),
    )?;
    write_line(
        output,
        "  reason string? @description(\"Optional plan-level intent or rationale. Logged when plan is rejected (e.g. empty steps).\")",
    )?;
    write_line(output, "}")?;

    Ok(())
}

/// Extract nested schemas from $defs or definitions and add to type_names mapping
fn extract_nested_schemas(
    schema: &Value,
    _schemas: &mut HashMap<String, Value>,
    type_names: &mut HashMap<String, String>,
) {
    if let Some(schema_obj) = schema.as_object() {
        // Check $defs (JSON Schema 2020-12)
        if let Some(defs) = schema_obj.get("$defs").and_then(|v| v.as_object()) {
            for def_name in defs.keys() {
                // Map def name to itself (BAML type name = Rust type name)
                type_names.insert(def_name.clone(), def_name.clone());
            }
        }

        // Check definitions (JSON Schema draft-07)
        if let Some(defs) = schema_obj.get("definitions").and_then(|v| v.as_object()) {
            for def_name in defs.keys() {
                // Map def name to itself (BAML type name = Rust type name)
                type_names.insert(def_name.clone(), def_name.clone());
            }
        }

        // Recursively check nested objects
        for value in schema_obj.values() {
            extract_nested_schemas(value, _schemas, type_names);
        }
    } else if let Some(schema_array) = schema.as_array() {
        for item in schema_array {
            extract_nested_schemas(item, _schemas, type_names);
        }
    }
}
