//! BAML tool interface generation with FSM-aware prompting hints
//!
//! Generates BAML tool interface files with detailed descriptions and examples
//! following Anthropic's best practices for tool use prompting.

use std::collections::{HashMap, HashSet};

use baml_rt_tools::{tool_catalog::resolve_manifest_tools, tools::ToolFunctionMetadata};
#[cfg(feature = "clickup")]
use baml_tool_links::baml_tools_clickup;
#[cfg(feature = "notion")]
use baml_tool_links::baml_tools_notion;
#[cfg(feature = "slack")]
use baml_tool_links::baml_tools_slack;
use baml_tool_links::{baml_rt_tools_claude, baml_tools_calculator, baml_tools_system};
use serde_json::Value;

use crate::builder::{
    error::{Result, write_line},
    schema_to_baml,
};

fn escape_baml_description(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Generate BAML tool interface file with FSM-aware prompting hints
pub fn render_baml_tool_interfaces(tool_names: &[String]) -> Result<String> {
    // Force link so inventory sees these metadata registrations (regen_fixtures + builder).
    let _ = baml_tools_calculator::support_calculate_metadata;
    let _ = baml_rt_tools_claude::metadata::claude_dev_metadata;
    let _ = baml_tools_system::metadata::system_internal_a2a_metadata;
    #[cfg(feature = "clickup")]
    let _ = baml_tools_clickup::ClickUpTool::new;
    #[cfg(feature = "notion")]
    let _ = baml_tools_notion::NotionTool::new;
    #[cfg(feature = "slack")]
    let _ = baml_tools_slack::SlackTool::new;
    let tool_metadata = resolve_manifest_tools(tool_names)?;

    let mut output = String::new();

    // Header with FSM documentation
    write_line(&mut output, "// Auto-generated tool interfaces")?;
    write_line(
        &mut output,
        "// This file is auto-generated - do not edit manually",
    )?;
    write_line(&mut output, "")?;
    write_line(
        &mut output,
        "// FSM (Finite State Machine) Tool Session Protocol:",
    )?;
    write_line(
        &mut output,
        "// All host tools use a session-based FSM with strict state transitions:",
    )?;
    write_line(
        &mut output,
        "// 1. Open: Must be the FIRST step - opens a tool session",
    )?;
    write_line(
        &mut output,
        "// 2. Send: Can occur AFTER Open, including multiple times across a session",
    )?;
    write_line(
        &mut output,
        "// 3. Read: Retrieves output/progress using explicit read input",
    )?;
    write_line(&mut output, "// 4. Finish: Closes the session gracefully")?;
    write_line(&mut output, "// 5. Abort: Closes the session with an error")?;
    write_line(&mut output, "//")?;
    write_line(&mut output, "// CRITICAL FSM RULES:")?;
    write_line(&mut output, "// - Open MUST come before any Send step")?;
    write_line(
        &mut output,
        "// - Open may include 'initial_input' only when the step schema defines that field",
    )?;
    write_line(
        &mut output,
        "// - Send uses 'input' field (for subsequent inputs)",
    )?;
    write_line(
        &mut output,
        "// - Use Read to fetch pending output/chunks; Read may repeat between Send steps",
    )?;
    write_line(
        &mut output,
        "// - Always Finish or Abort to close the session",
    )?;
    write_line(&mut output, "")?;
    write_line(&mut output, "// Shared standard planning types")?;
    write_line(&mut output, "class StandardAgentPlanStep {")?;
    write_line(&mut output, "  agent_package string")?;
    write_line(&mut output, "  agent_instance_id string")?;
    write_line(&mut output, "  sub_message string")?;
    write_line(&mut output, "}")?;
    write_line(&mut output, "")?;
    write_line(&mut output, "class StandardStructuredPlan {")?;
    write_line(&mut output, "  intent_description string")?;
    write_line(&mut output, "  objective string")?;
    write_line(&mut output, "  plan_steps StandardAgentPlanStep[]")?;
    write_line(&mut output, "}")?;
    write_line(&mut output, "")?;
    write_line(&mut output, "class SessionContext {")?;
    write_line(&mut output, "  contract_version string")?;
    write_line(&mut output, "  session_open bool")?;
    write_line(&mut output, "  allowed_ops string[]")?;
    write_line(&mut output, "  scope_ref string?")?;
    write_line(&mut output, "  output_ref string?")?;
    write_line(&mut output, "  evidence_ref string?")?;
    write_line(&mut output, "}")?;
    write_line(&mut output, "")?;
    write_line(&mut output, "class HistoryContext {")?;
    write_line(&mut output, "  hop int")?;
    write_line(&mut output, "  op string")?;
    write_line(&mut output, "  status string")?;
    write_line(&mut output, "  truncated bool")?;
    write_line(&mut output, "  cursor string?")?;
    write_line(&mut output, "  payload string?")?;
    write_line(&mut output, "}")?;
    write_line(&mut output, "")?;
    // --- Domain type generation ---
    //
    // Tools that carry a `baml_decl` (generated by `#[derive(BamlType)]`) emit
    // their type declarations directly. Tools without `baml_decl` fall back to
    // the `schema_to_baml` JSON Schema conversion pipeline.
    let mut emitted_decl_types: HashSet<String> = HashSet::new();
    let mut macro_decls = String::new();

    // Pass 1: collect pre-rendered BAML declarations from BamlType-enabled tools.
    for tool in &tool_metadata {
        if let Some(decl) = &tool.baml_decl {
            // Track the type names from this tool so schema_to_baml skips them.
            emitted_decl_types.insert(tool.input_type.name.clone());
            emitted_decl_types.insert(tool.output_type.name.clone());
            if tool.open_input_type.name != "()" {
                emitted_decl_types.insert(tool.open_input_type.name.clone());
            }

            if !macro_decls.is_empty() {
                macro_decls.push('\n');
            }
            macro_decls.push_str(decl);
            macro_decls.push('\n');
        }
    }

    if !macro_decls.is_empty() {
        write_line(
            &mut output,
            "// Domain types generated from #[derive(BamlType)]",
        )?;
        write_line(&mut output, &macro_decls)?;
    }

    // Pass 2: for tools WITHOUT baml_decl, fall back to schema_to_baml.
    let mut schemas = HashMap::new();
    let mut type_names = HashMap::new();

    for tool in &tool_metadata {
        // Skip tools that already provided their types via baml_decl.
        if tool.baml_decl.is_some() {
            continue;
        }

        extract_nested_schemas(&tool.input_schema, &mut schemas, &mut type_names);
        extract_nested_schemas(&tool.output_schema, &mut schemas, &mut type_names);
        if tool.open_input_type.name != "()" {
            extract_nested_schemas(&tool.open_input_schema, &mut schemas, &mut type_names);
        }

        // Only add schemas for types not already emitted by baml_decl.
        if !emitted_decl_types.contains(&tool.input_type.name) {
            schemas.insert(tool.input_type.name.clone(), tool.input_schema.clone());
            type_names.insert(tool.input_type.name.clone(), tool.input_type.name.clone());
        }

        if !emitted_decl_types.contains(&tool.output_type.name) {
            schemas.insert(tool.output_type.name.clone(), tool.output_schema.clone());
            type_names.insert(tool.output_type.name.clone(), tool.output_type.name.clone());
        }

        if tool.open_input_type.name != "()"
            && !emitted_decl_types.contains(&tool.open_input_type.name)
        {
            schemas.insert(
                tool.open_input_type.name.clone(),
                tool.open_input_schema.clone(),
            );
            type_names.insert(
                tool.open_input_type.name.clone(),
                tool.open_input_type.name.clone(),
            );
        }
    }

    if !schemas.is_empty() {
        let domain_types = schema_to_baml::generate_baml_types_from_schemas(&schemas, &type_names)?;
        if !domain_types.is_empty() {
            write_line(&mut output, "// Domain types generated from JSON schemas")?;
            write_line(&mut output, &domain_types)?;
        }
    }

    for tool in &tool_metadata {
        generate_tool_baml_interface(&mut output, tool)?;
        write_line(&mut output, "")?;
    }

    Ok(output)
}

fn schema_allows_empty_or_null_open_input(schema: &Value) -> bool {
    match schema {
        Value::Null => true,
        Value::Object(map) => {
            if let Some(any_of) = map.get("anyOf").and_then(Value::as_array)
                && any_of.iter().any(schema_allows_empty_or_null_open_input)
            {
                return true;
            }
            if let Some(one_of) = map.get("oneOf").and_then(Value::as_array)
                && one_of.iter().any(schema_allows_empty_or_null_open_input)
            {
                return true;
            }
            if map
                .get("type")
                .and_then(Value::as_str)
                .is_some_and(|t| t == "null")
            {
                return true;
            }

            let type_allows_object = match map.get("type") {
                Some(Value::String(t)) => t == "object",
                Some(Value::Array(types)) => types
                    .iter()
                    .filter_map(Value::as_str)
                    .any(|t| t == "object" || t == "null"),
                Some(_) => false,
                None => map.contains_key("properties") || map.contains_key("required"),
            };
            if !type_allows_object {
                return false;
            }

            let has_required = map
                .get("required")
                .and_then(Value::as_array)
                .map(|arr| !arr.is_empty())
                .unwrap_or(false);
            if has_required {
                return false;
            }

            let min_properties = map
                .get("minProperties")
                .and_then(Value::as_u64)
                .unwrap_or(0);
            min_properties == 0
        }
        _ => false,
    }
}

fn generate_tool_baml_interface(output: &mut String, tool: &ToolFunctionMetadata) -> Result<()> {
    // Use the derived class name from metadata
    let class_name = &tool.class_name;

    // Use the actual type names from metadata
    let open_input_type_name = &tool.open_input_type.name;
    let input_type_name = &tool.input_type.name;

    let open_step_name = format!("{}OpenStep", class_name);
    let send_step_name = format!("{}SendStep", class_name);
    let read_step_name = format!("{}ReadStep", class_name);
    let finish_step_name = format!("{}FinishStep", class_name);
    let abort_step_name = format!("{}AbortStep", class_name);
    let step_union_name = format!("{}SessionStep", class_name);
    let plan_type_name = format!("{}SessionPlan", class_name);
    let access_note = tool
        .access
        .map(|access| format!(" Access: {}.", access))
        .unwrap_or_default();

    let tool_name = tool.name.to_string();
    let is_claude_or_a2a = tool_name.starts_with("claude/")
        || tool_name.contains("/a2a")
        || tool_name.contains("_a2a");

    let send_input_desc = if is_claude_or_a2a {
        "Conversational message payload. Set text to a non-empty string. Never null, never omit text."
    } else {
        "Payload for this step."
    };
    let step_desc = if is_claude_or_a2a {
        "Emit exactly one FSM step. Choose op from allowed_ops. For Send, input.text MUST be a non-empty string message — never null. After Send, use Read to receive the response before sending again or finishing."
    } else {
        "Emit exactly one FSM step. Choose op from allowed_ops. After Send, prefer Read before further Send/Finish so you consume tool output and status."
    };
    let read_input_desc = "Read payload for this step.";

    // Generate distinct step types for each FSM operation
    write_line(output, &format!("class {} {{", open_step_name))?;
    write_line(output, "  op \"Open\"")?;
    // Skip initial_input for unit types or schemas with no properties (no meaningful open payload).
    let open_schema_has_properties = tool
        .open_input_schema
        .get("properties")
        .and_then(|p| p.as_object())
        .map(|m| !m.is_empty())
        .unwrap_or(false);
    if open_input_type_name != "()"
        && open_input_type_name != "null"
        && open_input_type_name != "void"
        && open_schema_has_properties
    {
        let open_is_optional = schema_allows_empty_or_null_open_input(&tool.open_input_schema);
        let optional_suffix = if open_is_optional { "?" } else { "" };
        let initial_input_desc = if open_is_optional {
            "Optional open payload."
        } else {
            "Required open payload."
        };
        write_line(
            output,
            &format!(
                "  initial_input {}{} @description(\"{}\")",
                open_input_type_name, optional_suffix, initial_input_desc
            ),
        )?;
    }
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", send_step_name))?;
    write_line(output, "  op \"Send\"")?;
    write_line(
        output,
        &format!(
            "  input {} @description(\"{}\")",
            input_type_name, send_input_desc
        ),
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", read_step_name))?;
    write_line(output, "  op \"Read\"")?;
    write_line(
        output,
        &format!(
            "  input {} @description(\"{}\")",
            input_type_name,
            escape_baml_description(read_input_desc)
        ),
    )?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", finish_step_name))?;
    write_line(output, "  op \"Finish\"")?;
    write_line(output, "}")?;
    write_line(output, "")?;

    write_line(output, &format!("class {} {{", abort_step_name))?;
    write_line(output, "  op \"Abort\"")?;
    write_line(output, "}")?;
    write_line(output, "")?;

    // Generate union type for all step types
    write_line(
        output,
        &format!(
            "type {} = {} | {} | {} | {} | {}",
            step_union_name,
            open_step_name,
            send_step_name,
            read_step_name,
            finish_step_name,
            abort_step_name
        ),
    )?;
    write_line(output, "")?;

    // Generate session plan with FSM guidance and example. Runtime resolves the tool from the
    // builder-generated manifest mapping (function name -> plan type).
    write_line(output, &format!("class {} {{", plan_type_name))?;
    write_line(
        output,
        &format!(
            "  step {} @description(\"{}{}\")",
            step_union_name, step_desc, access_note
        ),
    )?;
    write_line(output, "}")?;

    Ok(())
}

/// Extract nested schemas from $defs or definitions and add to type_names mapping
fn extract_nested_schemas(
    schema: &Value,
    _schemas: &mut HashMap<String, Value>,
    type_names: &mut HashMap<String, String>,
) {
    if let Some(schema_obj) = schema.as_object() {
        // Check $defs (JSON Schema 2020-12)
        if let Some(defs) = schema_obj.get("$defs").and_then(|v| v.as_object()) {
            for def_name in defs.keys() {
                // Map def name to itself (BAML type name = Rust type name)
                type_names.insert(def_name.clone(), def_name.clone());
            }
        }

        // Check definitions (JSON Schema draft-07)
        if let Some(defs) = schema_obj.get("definitions").and_then(|v| v.as_object()) {
            for def_name in defs.keys() {
                // Map def name to itself (BAML type name = Rust type name)
                type_names.insert(def_name.clone(), def_name.clone());
            }
        }

        // Recursively check nested objects
        for value in schema_obj.values() {
            extract_nested_schemas(value, _schemas, type_names);
        }
    } else if let Some(schema_array) = schema.as_array() {
        for item in schema_array {
            extract_nested_schemas(item, _schemas, type_names);
        }
    }
}
