//! Compiler implementations for BAML and TypeScript
//!
//! TypeScript compilation is delegated to `tsc` (the official TypeScript compiler)
//! via subprocess. This provides full type checking — not just syntax checking —
//! and eliminates the heavy OXC dependency tree.
//!
//! The compiler expects each agent to have:
//! - `tsconfig.json` in the agent root (created by bootstrap, with fixed settings)
//! - `src/baml-runtime.d.ts` (generated by `RuntimeTypeGenerator` before compilation)

use std::{ffi::OsStr, fs, path::Path, process::Command};

use baml_rt_tools::get_session_coordination_baml_for_tools;

use crate::builder::{
    a2a_shim_gen::render_a2a_shim,
    baml_gen::render_baml_tool_interfaces,
    baml_signature_gen::{extract_baml_signatures, session_plan_functions_map},
    error::{BamlBuilderError, Result},
    traits::{TypeGenerator, TypeScriptCompiler},
    ts_gen::{load_manifest_tools, render_ts_declarations},
    types::{AgentDir, BuildDir},
};

/// The canonical tsconfig settings for BAML agents.
///
/// This is written to `tsconfig.json` in the agent root by bootstrap and
/// regenerated by the build pipeline. Agents should not need to customise this.
pub const TSCONFIG_JSON: &str = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": false,
    "sourceMap": false,
    "isolatedModules": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
"#;

/// TypeScript compiler that delegates to `tsc` (TypeScript Compiler).
///
/// Provides full type checking in addition to compilation. Requires `tsc` to be
/// available on PATH (either directly or via `npx`).
///
/// The agent directory must contain a `tsconfig.json` (created by bootstrap) and
/// `src/baml-runtime.d.ts` (written by `RuntimeTypeGenerator`).
pub struct TscCompiler;

impl TscCompiler {
    pub fn new() -> Self {
        Self
    }

    /// Type-check only (no output). Runs `tsc --noEmit` against the agent's tsconfig.
    pub async fn typecheck(&self, agent_dir: &AgentDir) -> Result<()> {
        ensure_tsconfig(agent_dir)?;
        run_tsc(agent_dir.as_path(), &["--noEmit"])
    }

    /// Post-process compiled JS files for QuickJS compatibility.
    ///
    /// - Strips trailing `export {}` / `export {};` (QuickJS evaluates scripts, not modules)
    /// - Prepends the A2A runtime shim to `index.js`
    fn post_process(&self, dist_dir: &Path) -> Result<()> {
        for path in collect_js_files(dist_dir)? {
            let mut content = fs::read_to_string(&path)?;

            // QuickJS does not support ESM; strip trailing empty export so script evaluates.
            let trimmed = content.trim_end();
            if trimmed.ends_with("export {};") {
                content = trimmed
                    .strip_suffix("export {};")
                    .unwrap_or(trimmed)
                    .trim_end()
                    .to_string();
            } else if trimmed.ends_with("export {}") {
                content = trimmed
                    .strip_suffix("export {}")
                    .unwrap_or(trimmed)
                    .trim_end()
                    .to_string();
            }

            if path.file_name() == Some(OsStr::new("index.js")) {
                let a2a_shim = render_a2a_shim()?;
                content = format!("{}\n{}", a2a_shim.trim_end(), content);
            }

            fs::write(&path, &content)?;
        }
        Ok(())
    }
}

impl Default for TscCompiler {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl TypeScriptCompiler for TscCompiler {
    async fn compile(&self, agent_dir: &AgentDir, dist_dir: &Path) -> Result<()> {
        fs::create_dir_all(dist_dir)?;
        ensure_tsconfig(agent_dir)?;

        // --outDir overrides anything in tsconfig; lets us target the build dir.
        run_tsc(
            agent_dir.as_path(),
            &["--outDir", &dist_dir.display().to_string()],
        )?;

        self.post_process(dist_dir)?;
        Ok(())
    }
}

// ── tsc invocation helpers ──────────────────────────────────────────────────

/// Ensure the agent has a `tsconfig.json` with the canonical settings.
fn ensure_tsconfig(agent_dir: &AgentDir) -> Result<()> {
    write_canonical_tsconfig(agent_dir.as_path())
}

pub fn write_canonical_tsconfig(root: &Path) -> Result<()> {
    let tsconfig_path = root.join("tsconfig.json");
    atomic_write(&tsconfig_path, TSCONFIG_JSON.as_bytes())
}

/// Locate and run `tsc` with the agent's tsconfig.
///
/// Tries `tsc` on PATH first, then falls back to `npx tsc`.
fn run_tsc(project_dir: &Path, extra_args: &[&str]) -> Result<()> {
    let (program, base_args) = find_tsc(project_dir)?;

    let mut cmd = Command::new(&program);
    for arg in &base_args {
        cmd.arg(arg);
    }
    cmd.arg("--project").arg(project_dir);
    for arg in extra_args {
        cmd.arg(arg);
    }

    let output = cmd.output().map_err(|e| {
        BamlBuilderError::InvalidArgument(format!("Failed to execute {program}: {e}"))
    })?;

    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        let diagnostics = if !stdout.is_empty() {
            stdout.to_string()
        } else {
            stderr.to_string()
        };
        return Err(BamlBuilderError::TypeScriptCompilation {
            diagnostics: diagnostics.trim().to_string(),
        });
    }

    Ok(())
}

/// Find a working `tsc` command. Returns `(program, extra_args)`.
fn find_tsc(start_dir: &Path) -> Result<(String, Vec<String>)> {
    // Try tsc directly
    if let Ok(output) = Command::new("tsc").arg("--version").output()
        && output.status.success()
    {
        return Ok(("tsc".to_string(), vec![]));
    }

    if let Ok(start_dir) = start_dir.canonicalize() {
        for root in start_dir.ancestors() {
            for candidate in [
                root.join("node_modules").join(".bin").join("tsc"),
                // Workspace convention: frontend deps are installed once under
                // repo-root/web/node_modules, even when the builder runs from a crate dir.
                root.join("web")
                    .join("node_modules")
                    .join(".bin")
                    .join("tsc"),
            ] {
                if !candidate.is_file() {
                    continue;
                }
                if let Ok(output) = Command::new(&candidate).arg("--version").output()
                    && output.status.success()
                {
                    return Ok((candidate.to_string_lossy().into_owned(), vec![]));
                }
            }
            if root.join(".git").exists() {
                break;
            }
        }
    }

    // Try npx tsc (--yes to auto-install if needed)
    if let Ok(output) = Command::new("npx")
        .args(["--yes", "tsc", "--version"])
        .output()
        && output.status.success()
    {
        return Ok((
            "npx".to_string(),
            vec!["--yes".to_string(), "tsc".to_string()],
        ));
    }

    Err(BamlBuilderError::InvalidArgument(
        "TypeScript compiler (tsc) not found. Install with: npm install -g typescript".to_string(),
    ))
}

/// Recursively collect `.js` files under a directory.
fn collect_js_files(dir: &Path) -> Result<Vec<std::path::PathBuf>> {
    let mut files = Vec::new();
    collect_js_files_recursive(dir, &mut files)?;
    Ok(files)
}

fn collect_js_files_recursive(dir: &Path, files: &mut Vec<std::path::PathBuf>) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_js_files_recursive(&path, files)?;
        } else if path.extension() == Some(OsStr::new("js")) {
            files.push(path);
        }
    }
    Ok(())
}

// ── Type generator (unchanged — does not use OXC) ──────────────────────────

/// Type generator for runtime declarations.
///
/// Writes `baml-runtime.d.ts` into the agent's `src/` directory so that both
/// `tsc` and IDEs can resolve the types without any temp-dir indirection.
pub struct RuntimeTypeGenerator;

impl RuntimeTypeGenerator {
    pub fn new() -> Self {
        Self
    }
}

impl Default for RuntimeTypeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl TypeGenerator for RuntimeTypeGenerator {
    async fn generate(&self, agent_dir: &AgentDir, build_dir: &BuildDir) -> Result<()> {
        use std::collections::HashMap;

        use baml_runtime::BamlRuntime;

        let baml_src = agent_dir.baml_src();

        // Generate BAML tool interfaces into build_dir/baml_src so the packaged baml_src
        // contains them (packager adds build_dir/baml_src to the tar).
        // When build_dir/baml_src does not exist (e.g. bootstrap), copy source baml_src so the runtime can load it.
        let baml_src_build = build_dir.join("baml_src");
        if !baml_src_build.exists() {
            copy_dir_all_impl(&baml_src, &baml_src_build)?;
        }
        let tool_names = load_manifest_tools(&baml_src)?;
        if !tool_names.is_empty() {
            let baml_interfaces = render_baml_tool_interfaces(&tool_names)?;
            let baml_output_path = baml_src_build.join("generated_tools.baml");
            if let Some(parent) = baml_output_path.parent() {
                fs::create_dir_all(parent).map_err(BamlBuilderError::Io)?;
            }
            atomic_write(&baml_output_path, baml_interfaces.as_bytes())?;

            // Emit session coordination BAML from tool crates that registered a provider (e.g. claude/dev).
            if let Some(coord_baml) = get_session_coordination_baml_for_tools(&tool_names)? {
                let coord_path = baml_src_build.join("generated_session_coordination.baml");
                atomic_write(&coord_path, coord_baml.as_bytes())?;
            }
        }

        // Load BAML runtime from build_dir/baml_src to discover functions
        let env_vars: HashMap<String, String> = HashMap::new();
        let feature_flags = internal_baml_core::feature_flags::FeatureFlags::default();

        let runtime = BamlRuntime::from_directory(&baml_src_build, env_vars, feature_flags)
            .map_err(|e| BamlBuilderError::RuntimeLoadFailed { source: e })?;

        let ir_signature = extract_baml_signatures(&runtime)?;
        let session_plan_map = session_plan_functions_map(&ir_signature);
        let declarations = render_ts_declarations(&ir_signature, &session_plan_map)?;

        // Write baml-runtime.d.ts into agent's src/ so tsc resolves it directly.
        let src_dts = agent_dir.src().join("baml-runtime.d.ts");
        if let Some(parent) = src_dts.parent() {
            fs::create_dir_all(parent)?;
        }
        atomic_write(&src_dts, declarations.as_bytes())?;

        // Also write to build_dir/dist/ for packaging (the .d.ts is included in the tar).
        let dist_dts = build_dir.join("dist").join("baml-runtime.d.ts");
        if let Some(parent) = dist_dts.parent() {
            fs::create_dir_all(parent)?;
        }
        atomic_write(&dist_dts, declarations.as_bytes())?;

        // Emit session-plan function map so the runtime can resolve tool from the invoking
        // function name (no reliance on __type in prompt output).
        if !session_plan_map.is_empty() {
            let manifest_path = build_dir.join("session_plan_functions.json");
            let json =
                serde_json::to_string_pretty(&session_plan_map).map_err(BamlBuilderError::Json)?;
            atomic_write(&manifest_path, json.as_bytes())?;
        }

        Ok(())
    }
}

fn copy_dir_all_impl(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst).map_err(BamlBuilderError::Io)?;
    for entry in fs::read_dir(src).map_err(BamlBuilderError::Io)? {
        let entry = entry.map_err(BamlBuilderError::Io)?;
        let path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if path.is_dir() {
            copy_dir_all_impl(&path, &dst_path)?;
        } else {
            fs::copy(&path, &dst_path).map_err(BamlBuilderError::Io)?;
        }
    }
    Ok(())
}

/// Write `data` to a temporary file in the same directory, then atomically rename
/// over `dest`.  On Unix `rename(2)` is atomic, so concurrent readers never see
/// a half-written file — they get either the old content or the new content.
pub(crate) fn atomic_write(dest: &Path, data: &[u8]) -> Result<()> {
    use std::io::Write;

    let parent = dest.parent().unwrap_or(Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(parent)?;
    tmp.write_all(data)?;
    tmp.persist(dest)
        .map_err(|e| BamlBuilderError::Io(e.error))?;
    Ok(())
}
