//! Compiler implementations for BAML and TypeScript
//!
//! TypeScript compilation is delegated to `tsc` (the official TypeScript compiler)
//! via subprocess. This provides full type checking — not just syntax checking —
//! and eliminates the heavy OXC dependency tree.
//!
//! The compiler expects each agent to have:
//! - `tsconfig.json` in the agent root (created by bootstrap, with fixed settings)
//! - `src/baml-runtime.d.ts` (generated by `RuntimeTypeGenerator` before compilation)
//!
//! Submodules: `tsc`, `quickjs_post_process`, `runtime_type_gen`, and `atomic_io`.

mod atomic_io;
mod quickjs_post_process;
mod runtime_type_gen;
mod tsc;

pub use quickjs_post_process::{
    post_process_js_for_quickjs, strip_trailing_empty_export_for_quickjs,
};
pub use runtime_type_gen::RuntimeTypeGenerator;
pub use tsc::{TSCONFIG_JSON, TscCompiler, write_canonical_tsconfig};
