//! TypeScript compilation via `tsc` and canonical `tsconfig.json`.

use std::{fs, path::Path, process::Command};

use tokio::task;

use super::{atomic_io::atomic_write, quickjs_post_process::post_process_dist_dir};
use crate::builder::{
    error::{BamlBuilderError, Result},
    traits::TypeScriptCompiler,
    types::AgentDir,
};

/// The canonical tsconfig settings for BAML agents.
///
/// This is written to `tsconfig.json` in the agent root by bootstrap and
/// regenerated by the build pipeline. Agents should not need to customise this.
///
/// **`rootDir`** is required explicitly: TypeScript 6 defaults `rootDir` to the directory
/// containing `tsconfig.json` unless set; sources under `src/` then trigger TS5011 unless
/// `rootDir` is explicitly `"./src"` (must match the inferred common source path; see
/// <https://aka.ms/ts6> migration notes).
pub const TSCONFIG_JSON: &str = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": false,
    "sourceMap": false,
    "isolatedModules": true,
    "rootDir": "./src"
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
"#;

/// TypeScript compiler that delegates to `tsc` (TypeScript Compiler).
///
/// Provides full type checking in addition to compilation. Requires `tsc` to be
/// available on PATH (either directly or via `npx`).
///
/// The agent directory must contain a `tsconfig.json` (created by bootstrap) and
/// `src/baml-runtime.d.ts` (written by `RuntimeTypeGenerator`).
pub struct TscCompiler;

impl TscCompiler {
    pub fn new() -> Self {
        Self
    }

    /// Type-check only (no output). Runs `tsc --noEmit` against the agent's tsconfig.
    pub async fn typecheck(&self, agent_dir: &AgentDir) -> Result<()> {
        let agent_dir = agent_dir.clone();
        task::spawn_blocking(move || {
            ensure_tsconfig(&agent_dir)?;
            run_tsc(agent_dir.as_path(), &["--noEmit"])
        })
        .await
        .map_err(|e| BamlBuilderError::BlockingTaskJoin { source: e })?
    }
}

impl Default for TscCompiler {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl TypeScriptCompiler for TscCompiler {
    async fn compile(&self, agent_dir: &AgentDir, dist_dir: &Path) -> Result<()> {
        let agent_dir = agent_dir.clone();
        let dist_dir = dist_dir.to_path_buf();

        task::spawn_blocking(move || {
            fs::create_dir_all(&dist_dir)?;
            ensure_tsconfig(&agent_dir)?;

            // --outDir overrides anything in tsconfig; lets us target the build dir.
            let out_dir_arg = dist_dir.display().to_string();
            run_tsc(agent_dir.as_path(), &["--outDir", out_dir_arg.as_str()])?;

            post_process_dist_dir(&dist_dir)?;
            Ok(())
        })
        .await
        .map_err(|e| BamlBuilderError::BlockingTaskJoin { source: e })?
    }
}

// ── tsc invocation helpers ──────────────────────────────────────────────────

fn ensure_tsconfig(agent_dir: &AgentDir) -> Result<()> {
    write_canonical_tsconfig(agent_dir.as_path())
}

pub fn write_canonical_tsconfig(root: &Path) -> Result<()> {
    let tsconfig_path = root.join("tsconfig.json");
    atomic_write(&tsconfig_path, TSCONFIG_JSON.as_bytes())
}

/// Locate and run `tsc` with the agent's tsconfig.
///
/// Tries `tsc` on PATH first, then falls back to `npx tsc`.
fn run_tsc(project_dir: &Path, extra_args: &[&str]) -> Result<()> {
    let (program, base_args) = find_tsc(project_dir)?;

    // TS 6 + `npx tsc`: resolve a stable cwd and absolute `--project` so `rootDir` / `include`
    // in the agent tsconfig are not resolved against the wrong directory (CI TS5011).
    let project_dir = project_dir.canonicalize().map_err(|e| {
        BamlBuilderError::InvalidArgument(format!(
            "Failed to canonicalize agent dir {}: {e}",
            project_dir.display()
        ))
    })?;
    let tsconfig_path = project_dir.join("tsconfig.json");

    let mut cmd = Command::new(&program);
    cmd.current_dir(&project_dir);
    for arg in &base_args {
        cmd.arg(arg);
    }
    // Pass the config file path (not only the directory) so `tsc` never picks up a parent
    // tsconfig or a stale resolution path under TS 6+ (TS5011 / rootDir).
    cmd.arg("--project").arg(&tsconfig_path);
    for arg in extra_args {
        cmd.arg(arg);
    }

    let output = cmd.output().map_err(|e| {
        BamlBuilderError::InvalidArgument(format!("Failed to execute {program}: {e}"))
    })?;

    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        let diagnostics = if !stdout.is_empty() {
            stdout.to_string()
        } else {
            stderr.to_string()
        };
        return Err(BamlBuilderError::TypeScriptCompilation {
            diagnostics: diagnostics.trim().to_string(),
        });
    }

    Ok(())
}

/// Find a working `tsc` command. Returns `(program, extra_args)`.
fn find_tsc(start_dir: &Path) -> Result<(String, Vec<String>)> {
    // Try tsc directly
    if let Ok(output) = Command::new("tsc").arg("--version").output()
        && output.status.success()
    {
        return Ok(("tsc".to_string(), vec![]));
    }

    if let Ok(start_dir) = start_dir.canonicalize() {
        for root in start_dir.ancestors() {
            for candidate in [
                root.join("node_modules").join(".bin").join("tsc"),
                // Workspace convention: frontend deps are installed once under
                // repo-root/web/node_modules, even when the builder runs from a crate dir.
                root.join("web")
                    .join("node_modules")
                    .join(".bin")
                    .join("tsc"),
            ] {
                if !candidate.is_file() {
                    continue;
                }
                if let Ok(output) = Command::new(&candidate).arg("--version").output()
                    && output.status.success()
                {
                    return Ok((candidate.to_string_lossy().into_owned(), vec![]));
                }
            }
            if root.join(".git").exists() {
                break;
            }
        }
    }

    // Try npx tsc (--yes to auto-install if needed)
    if let Ok(output) = Command::new("npx")
        .args(["--yes", "tsc", "--version"])
        .output()
        && output.status.success()
    {
        return Ok((
            "npx".to_string(),
            vec!["--yes".to_string(), "tsc".to_string()],
        ));
    }

    Err(BamlBuilderError::InvalidArgument(
        "TypeScript compiler (tsc) not found. Install with: npm install -g typescript".to_string(),
    ))
}
