// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WeatherOutput = { location: string, temperature: string, temperature_f: bigint, condition: string, humidity: string, wind_speed: string, description: string, };
