//! Delivery sinks for interpreted batches.

use std::{
    fs::OpenOptions,
    io::Write,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, anyhow};
use async_trait::async_trait;
use integrations_clickup_client::ClickUpClient;
use serde_json::json;

use crate::model::{InvestigationTask, TaskBatch};

#[async_trait]
/// A destination for interpreted task batches.
pub trait TaskSink: Send {
    /// Stable sink identifier used in logs and error context.
    fn name(&self) -> &'static str;
    /// Delivers a batch to the sink.
    async fn deliver(&mut self, batch: &TaskBatch) -> Result<()>;
}

/// Sink that prints one JSON payload per batch to stdout.
pub struct StdoutSink {
    pretty: bool,
}

impl StdoutSink {
    /// Creates a stdout sink.
    ///
    /// When `pretty` is true the output is indented JSON.
    pub fn new(pretty: bool) -> Self {
        Self { pretty }
    }
}

#[async_trait]
impl TaskSink for StdoutSink {
    fn name(&self) -> &'static str {
        "stdout"
    }

    async fn deliver(&mut self, batch: &TaskBatch) -> Result<()> {
        let serialized = if self.pretty {
            serde_json::to_string_pretty(batch)
        } else {
            serde_json::to_string(batch)
        }
        .context("serializing task batch for stdout sink")?;
        println!("{serialized}");
        Ok(())
    }
}

/// Sink that appends each batch as one JSON line to a file.
pub struct JsonlFileSink {
    path: PathBuf,
}

impl JsonlFileSink {
    /// Creates a JSONL file sink.
    pub fn new(path: PathBuf) -> Self {
        Self { path }
    }

    /// Returns the output file path.
    pub fn path(&self) -> &Path {
        self.path.as_path()
    }
}

#[async_trait]
impl TaskSink for JsonlFileSink {
    fn name(&self) -> &'static str {
        "jsonl"
    }

    async fn deliver(&mut self, batch: &TaskBatch) -> Result<()> {
        if let Some(parent) = self.path.parent()
            && !parent.as_os_str().is_empty()
        {
            std::fs::create_dir_all(parent).with_context(|| {
                format!("creating parent directory for {}", self.path.display())
            })?;
        }

        let line = serde_json::to_string(batch).context("serializing task batch to jsonl")?;
        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.path)
            .with_context(|| format!("opening jsonl sink file {}", self.path.display()))?;
        writeln!(file, "{line}")
            .with_context(|| format!("writing jsonl sink file {}", self.path.display()))?;
        Ok(())
    }
}

/// Sink that maps derived investigation tasks into ClickUp tasks.
pub struct ClickUpSink {
    client: ClickUpClient,
    list_id: String,
    dry_run: bool,
}

impl ClickUpSink {
    /// Creates a ClickUp sink.
    ///
    /// When `dry_run` is true, no API writes are performed.
    pub fn new(list_id: String, dry_run: bool) -> Result<Self> {
        let list_id = list_id.trim().to_string();
        if list_id.is_empty() {
            return Err(anyhow!("clickup list_id must not be empty"));
        }

        Ok(Self {
            client: ClickUpClient::new(),
            list_id,
            dry_run,
        })
    }

    fn task_title(task: &InvestigationTask) -> String {
        const MAX_TITLE_LEN: usize = 240;
        let trimmed = task.title.trim();
        if trimmed.chars().count() <= MAX_TITLE_LEN {
            return trimmed.to_string();
        }

        let mut out = String::new();
        for ch in trimmed.chars().take(MAX_TITLE_LEN.saturating_sub(3)) {
            out.push(ch);
        }
        out.push_str("...");
        out
    }

    fn task_description(batch: &TaskBatch, task: &InvestigationTask) -> String {
        let refs = if task.sources.is_empty() {
            "none".to_string()
        } else {
            task.sources
                .iter()
                .map(|source| {
                    source
                        .permalink
                        .clone()
                        .unwrap_or_else(|| source.reference.clone())
                })
                .collect::<Vec<_>>()
                .join("\n")
        };

        format!(
            "Generated by baml-task-daemon\n\nProject: {}\nSource: {}\nPriority: {}\n\nInterpretation summary:\n{}\n\nTask detail:\n{}\n\nReferences:\n{}",
            batch.project.project_key,
            batch.source_label,
            task.priority,
            batch.interpretation.executive_summary,
            task.description,
            refs,
        )
    }
}

#[async_trait]
impl TaskSink for ClickUpSink {
    fn name(&self) -> &'static str {
        if self.dry_run {
            "clickup-dry-run"
        } else {
            "clickup"
        }
    }

    async fn deliver(&mut self, batch: &TaskBatch) -> Result<()> {
        if batch.derived_tasks.is_empty() {
            return Ok(());
        }

        if self.dry_run {
            tracing::info!(
                list_id = %self.list_id,
                derived_tasks = batch.derived_tasks.len(),
                "ClickUp sink dry-run enabled; no tasks created"
            );
            return Ok(());
        }

        let api_key = ClickUpClient::api_key().context("loading CLICKUP_API_KEY for sink")?;

        for task in &batch.derived_tasks {
            let body = json!({
                "name": Self::task_title(task),
                "description": Self::task_description(batch, task),
            });

            let request = self
                .client
                .post(&format!("/list/{}/task", self.list_id), &api_key)
                .json(&body);
            self.client
                .send_json(request)
                .await
                .with_context(|| format!("creating ClickUp task in list {}", self.list_id))?;
        }

        tracing::info!(
            list_id = %self.list_id,
            derived_tasks = batch.derived_tasks.len(),
            "Created ClickUp investigation tasks from interpretation batch"
        );
        Ok(())
    }
}
