apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: agentium
  namespace: argocd
spec:
  description: Agentium OS local k3d
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
