// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArithmeticOp } from "./ArithmeticOp";

export type ArithmeticInput = { operation: ArithmeticOp, a: number, b: number, };
