// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which ClickUp action to perform.
 */
export type ClickUpAction = "ListTeams" | "ListSpaces" | "ListLists" | "ListTasks" | "GetTask" | "CreateTask" | "UpdateTask";
