// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClickUpAction } from "./ClickUpAction";

/**
 * Input for the ClickUp tool.
 *
 * Uses a flat struct with an `action` discriminator instead of a Rust enum
 * so that BAML (which lacks sum types) can represent it as a single class
 * with an enum field. Per-action field requirements are validated at runtime
 * in [`ClickUpTool::execute`].
 */
export type ClickUpInput = { action: ClickUpAction, 
/**
 * Required for `ListSpaces`.
 */
team_id: string | null, 
/**
 * Required for `ListLists`.
 */
space_id: string | null, 
/**
 * Required for `ListTasks` and `CreateTask`.
 */
list_id: string | null, 
/**
 * Required for `GetTask` and `UpdateTask`.
 */
task_id: string | null, 
/**
 * Required for `CreateTask`.
 */
name: string | null, 
/**
 * The clickup-task description
 */
description: string | null, 
/**
 * ClickUp priority: 1 = urgent, 2 = high, 3 = normal, 4 = low.
 */
priority: number | null, 
/**
 * Task status string (e.g. \"in progress\"). Used by `UpdateTask`.
 */
status: string | null, };
