// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a single ClickUp task, projected from the API response.
 */
export type ClickUpTaskSummary = { id: string, name: string, status: string, url: string, assignees: Array<string>, priority: string | null, due_date: string | null, };
