// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A generic item returned by navigation actions (teams, spaces, lists).
 */
export type ClickUpItem = { id: string, name: string, 
/**
 * The kind of resource: "team", "space", or "list".
 */
kind: string, };
