// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClickUpItem } from "./ClickUpItem";
import type { ClickUpTaskSummary } from "./ClickUpTaskSummary";

/**
 * Output returned by every ClickUp tool action.
 *
 * Task actions populate `tasks`; navigation actions populate `items`.
 */
export type ClickUpOutput = { tasks: Array<ClickUpTaskSummary>, 
/**
 * Teams, spaces, or lists returned by navigation actions.
 */
items: Array<ClickUpItem>, message: string, };
