// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotionBlockSummary } from "./NotionBlockSummary";
import type { NotionPageSummary } from "./NotionPageSummary";
import type { NotionSource } from "./NotionSource";

export type NotionOutput = { pages: Array<NotionPageSummary>, blocks: Array<NotionBlockSummary>, next_cursor: string | null, has_more: boolean, sources: Array<NotionSource>, message: string, };
