// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Notion action to perform.
 */
export type NotionAction = "SearchPages" | "GetPage" | "GetPageBlocks";
