// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotionSearchPagesInput = { query: string | null, start_cursor: string | null, page_size: number | null, };
