// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotionAction } from "./NotionAction";

/**
 * Input for the Notion tool (single tool with action discriminator).
 */
export type NotionInput = { action: NotionAction, query: string | null, start_cursor: string | null, page_size: number | null, page_id: string | null, block_id: string | null, };
