// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotionBlockSummary = { id: string, block_type: string, text: string | null, has_children: boolean, };
