// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StringOp } from "./StringOp";

export type StringManipulationInput = { operation: StringOp, text: string, };
