//! Derive task_id, context_id, agent_id by graph traversal.
//!
//! These properties need not be written on every node; they can be derived by
//! parsing node ids or traversing edges. This enrichment runs after export parse
//! so consumers (filter_scope, sequence) continue to work without change.

use std::collections::HashMap;

use super::ExportedGraph;
use crate::vocabulary::a2a;

/// Edges that connect activities to their task (TaskExecution has task_id in id).
const EDGE_TO_TASK_EXECUTION: &[&str] = &["WAS_INVOKED_BY", "WAS_EXECUTED_BY", "WAS_UPDATED_BY"];
/// Edges from entity to activity (Task -[WAS_CREATED_BY]-> TaskExecution).
const EDGE_FROM_TASK: &[&str] = &["WAS_CREATED_BY"];
/// Edges from activity/entity with task_id to entity (Message). Propagates task_id to Message
/// so each user message gets its own task rect in the sequence diagram.
const EDGE_FROM_ACTIVITY_WITH_TASK: &[&str] = &["WAS_RECEIVED_BY", "WAS_SPAWNED_BY"];
/// Edges from entity to activity with task_id (entity was emitted/generated by activity).
/// Propagates task_id to the entity so assistant replies get their task's rect.
const EDGE_TO_ACTIVITY_WITH_TASK: &[&str] = &["WAS_EMITTED_BY"];
/// Edges to AgentRuntimeInstance (agent_id in id).
const EDGE_TO_AGENT: &[&str] = &["WAS_EXECUTED_BY", "WAS_INVOKED_BY"];

/// Parse task_id from node id. Returns Some if the id format encodes task_id.
fn parse_task_id_from_id(id: &str) -> Option<String> {
    if let Some(tid) = id.strip_prefix("task_execution_") {
        return Some(tid.to_string());
    }
    if let Some(tid) = id.strip_prefix("task:") {
        return Some(tid.to_string());
    }
    if let Some(rest) = id.strip_prefix("task_state:") {
        return rest.split(':').next().map(String::from);
    }
    if let Some(rest) = id.strip_prefix("artifact:") {
        return rest.split(':').next().map(String::from);
    }
    None
}

/// Parse context_id from node id.
fn parse_context_id_from_id(id: &str) -> Option<String> {
    if let Some(rest) = id.strip_prefix("message:") {
        return rest.split(':').next().map(String::from);
    }
    if let Some(rest) = id.strip_prefix("message_processing:") {
        return rest.split(':').next().map(String::from);
    }
    None
}

/// Parse agent_id from node id.
fn parse_agent_id_from_id(id: &str) -> Option<String> {
    if let Some(aid) = id.strip_prefix("agent_instance:") {
        return Some(aid.to_string());
    }
    None
}

/// Enrich nodes with task_id, context_id, agent_id derived by id parsing and traversal.
pub fn enrich_derived_properties(graph: &mut ExportedGraph) {
    let mut task_id_by_node: HashMap<String, String> = HashMap::new();
    let mut context_id_by_node: HashMap<String, String> = HashMap::new();
    let mut agent_id_by_node: HashMap<String, String> = HashMap::new();

    for node in &graph.nodes {
        if let Some(tid) = parse_task_id_from_id(&node.id) {
            task_id_by_node.insert(node.id.clone(), tid);
        }
        if let Some(cid) = parse_context_id_from_id(&node.id) {
            context_id_by_node.insert(node.id.clone(), cid);
        }
        if let Some(aid) = parse_agent_id_from_id(&node.id) {
            agent_id_by_node.insert(node.id.clone(), aid);
        }
    }

    // Propagate task_id: follow edges to TaskExecution or Task.
    for _ in 0..3 {
        let mut changed = false;
        for edge in &graph.edges {
            let from_tid = task_id_by_node.get(&edge.from).cloned();
            let to_tid = task_id_by_node.get(&edge.to).cloned();
            if let (None, Some(tid)) = (from_tid.as_ref(), to_tid.as_ref())
                && (EDGE_TO_TASK_EXECUTION.contains(&edge.relation.as_str())
                    || EDGE_TO_ACTIVITY_WITH_TASK.contains(&edge.relation.as_str()))
            {
                task_id_by_node.insert(edge.from.clone(), tid.clone());
                changed = true;
            }
            if let (Some(tid), None) = (from_tid.as_ref(), to_tid.as_ref())
                && (EDGE_FROM_TASK.contains(&edge.relation.as_str())
                    || EDGE_FROM_ACTIVITY_WITH_TASK.contains(&edge.relation.as_str()))
            {
                task_id_by_node.insert(edge.to.clone(), tid.clone());
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }

    // Propagate agent_id: follow WAS_EXECUTED_BY/WAS_INVOKED_BY to AgentRuntimeInstance.
    for _ in 0..3 {
        let mut changed = false;
        for edge in &graph.edges {
            let to_aid = agent_id_by_node.get(&edge.to).cloned();
            if let Some(aid) = to_aid.as_ref()
                && EDGE_TO_AGENT.contains(&edge.relation.as_str())
                && agent_id_by_node
                    .insert(edge.from.clone(), aid.clone())
                    .is_none()
            {
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }

    // Propagate context_id: follow to message/message_processing (they have it in id).
    for _ in 0..3 {
        let mut changed = false;
        for edge in &graph.edges {
            let from_cid = context_id_by_node.get(&edge.from).cloned();
            let to_cid = context_id_by_node.get(&edge.to).cloned();
            if let (None, Some(cid)) = (from_cid.as_ref(), to_cid.as_ref()) {
                context_id_by_node.insert(edge.from.clone(), cid.clone());
                changed = true;
            }
            if let (Some(cid), None) = (from_cid.as_ref(), to_cid.as_ref()) {
                context_id_by_node.insert(edge.to.clone(), cid.clone());
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }

    for node in &mut graph.nodes {
        if node
            .properties
            .get(a2a::TASK_ID)
            .is_none_or(|v| v.as_str().unwrap_or("").is_empty())
            && let Some(tid) = task_id_by_node.get(&node.id)
        {
            node.properties.insert(
                a2a::TASK_ID.to_string(),
                serde_json::Value::String(tid.clone()),
            );
        }
        if node
            .properties
            .get(a2a::CONTEXT_ID)
            .is_none_or(|v| v.as_str().unwrap_or("").is_empty())
            && let Some(cid) = context_id_by_node.get(&node.id)
        {
            node.properties.insert(
                a2a::CONTEXT_ID.to_string(),
                serde_json::Value::String(cid.clone()),
            );
        }
        if node
            .properties
            .get(a2a::AGENT_ID)
            .is_none_or(|v| v.as_str().unwrap_or("").is_empty())
            && let Some(aid) = agent_id_by_node.get(&node.id)
        {
            node.properties.insert(
                a2a::AGENT_ID.to_string(),
                serde_json::Value::String(aid.clone()),
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        super::{ExportScope, ExportedEdge, ExportedNode},
        *,
    };
    use crate::vocabulary::a2a;

    #[test]
    fn enrich_derives_task_id_by_traversal() {
        let mut graph = ExportedGraph {
            nodes: vec![
                ExportedNode {
                    id: "task_execution_task-1".to_string(),
                    label: "TaskExecution".to_string(),
                    display_name: "TaskExec task-1".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(1),
                },
                super::super::ExportedNode {
                    id: "llm_call_ctx:msg:0".to_string(),
                    label: "LlmCall".to_string(),
                    display_name: "LLM".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(2),
                },
            ],
            edges: vec![ExportedEdge {
                from: "llm_call_ctx:msg:0".to_string(),
                to: "task_execution_task-1".to_string(),
                relation: "WAS_INVOKED_BY".to_string(),
                properties: HashMap::new(),
            }],
            scope: ExportScope::Task("task-1".to_string()),
        };
        enrich_derived_properties(&mut graph);
        let llm = graph
            .nodes
            .iter()
            .find(|n| n.id == "llm_call_ctx:msg:0")
            .unwrap();
        assert_eq!(
            llm.properties.get(a2a::TASK_ID).and_then(|v| v.as_str()),
            Some("task-1")
        );
    }

    #[test]
    fn enrich_derives_task_id_on_message_via_was_received_by() {
        // MessageProcessing -[WAS_INVOKED_BY]-> TaskExecution gives mp task_id.
        // MessageProcessing -[WAS_RECEIVED_BY]-> Message propagates task_id to Message.
        let mut graph = ExportedGraph {
            nodes: vec![
                ExportedNode {
                    id: "task_execution_task-2".to_string(),
                    label: "TaskExecution".to_string(),
                    display_name: "TaskExec task-2".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(1),
                },
                ExportedNode {
                    id: "message_processing:ctx:msg-2".to_string(),
                    label: "MessageProcessing".to_string(),
                    display_name: "MsgProc".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(2),
                },
                ExportedNode {
                    id: "message:ctx:msg-2".to_string(),
                    label: "Message".to_string(),
                    display_name: "msg".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(3),
                },
            ],
            edges: vec![
                ExportedEdge {
                    from: "message_processing:ctx:msg-2".to_string(),
                    to: "task_execution_task-2".to_string(),
                    relation: "WAS_INVOKED_BY".to_string(),
                    properties: HashMap::new(),
                },
                ExportedEdge {
                    from: "message_processing:ctx:msg-2".to_string(),
                    to: "message:ctx:msg-2".to_string(),
                    relation: "WAS_RECEIVED_BY".to_string(),
                    properties: HashMap::new(),
                },
            ],
            scope: ExportScope::Context("ctx".to_string()),
        };
        enrich_derived_properties(&mut graph);
        let msg = graph
            .nodes
            .iter()
            .find(|n| n.id == "message:ctx:msg-2")
            .unwrap();
        assert_eq!(
            msg.properties.get(a2a::TASK_ID).and_then(|v| v.as_str()),
            Some("task-2"),
            "Message should get task_id from MessageProcessing via WAS_RECEIVED_BY"
        );
    }

    #[test]
    fn enrich_derives_context_id_from_message_id() {
        let mut graph = ExportedGraph {
            nodes: vec![
                ExportedNode {
                    id: "message:ctx-1:msg-1".to_string(),
                    label: "Message".to_string(),
                    display_name: "msg".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(1),
                },
                ExportedNode {
                    id: "message_processing:ctx-1:msg-1".to_string(),
                    label: "MessageProcessing".to_string(),
                    display_name: "MsgProc".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(2),
                },
            ],
            edges: vec![ExportedEdge {
                from: "message:ctx-1:msg-1".to_string(),
                to: "message_processing:ctx-1:msg-1".to_string(),
                relation: "WAS_RECEIVED_BY".to_string(),
                properties: HashMap::new(),
            }],
            scope: ExportScope::Context("ctx-1".to_string()),
        };
        enrich_derived_properties(&mut graph);
        for node in &graph.nodes {
            assert_eq!(
                node.properties
                    .get(a2a::CONTEXT_ID)
                    .and_then(|v| v.as_str()),
                Some("ctx-1"),
                "node {} should have context_id",
                node.id
            );
        }
    }

    #[test]
    fn enrich_derives_agent_id_by_traversal() {
        let mut graph = ExportedGraph {
            nodes: vec![
                ExportedNode {
                    id: "agent_instance:tony".to_string(),
                    label: "AgentRuntimeInstance".to_string(),
                    display_name: "Agent tony".to_string(),
                    properties: HashMap::new(),
                    event_order: None,
                },
                ExportedNode {
                    id: "message_processing:ctx:msg".to_string(),
                    label: "MessageProcessing".to_string(),
                    display_name: "MsgProc".to_string(),
                    properties: HashMap::new(),
                    event_order: Some(1),
                },
            ],
            edges: vec![ExportedEdge {
                from: "message_processing:ctx:msg".to_string(),
                to: "agent_instance:tony".to_string(),
                relation: "WAS_EXECUTED_BY".to_string(),
                properties: HashMap::new(),
            }],
            scope: ExportScope::Context("ctx".to_string()),
        };
        enrich_derived_properties(&mut graph);
        let mp = graph
            .nodes
            .iter()
            .find(|n| n.id == "message_processing:ctx:msg")
            .unwrap();
        assert_eq!(
            mp.properties.get(a2a::AGENT_ID).and_then(|v| v.as_str()),
            Some("tony")
        );
    }
}
